### PR TITLE
Prefab langs

### PR DESCRIPTION
**Pull request by LeifAndersen**
```
Fix two issues:

1. Make non-terminal structs prefabs.

2. Require list-head from "helpers.rkt" in "pass.rkt".
```

### CODE REVIEW

**Comment by akeep** [comment]
Hey Leif,

I've got conflicting updates from you and Jens Axel Søgaard.  It looks like, Jens is making the the structs #:transparent and you are making them #:prefab.  Since #:prefab implies transparent, I'm inclined to take your pull request, but I've asked Jens if there is a reason he prefers #:transparent to #:prefab, so the three of us can hash it out.

-andy:)

**Comment by akeep** [comment]
Okay, Jens says this will work for him as well, so I'll go ahead and merge this.

**Comment by LeifAndersen** [comment]
Oh, I didn't realize Jens also had a PR. Woops.

I mostly just made it prefab to match with what was already there. Although
it doesn't really matter to me.

There is one advantage of using #:transparent though. We could make custom
printing for a language:
http://docs.racket-lang.org/reference/Printer_Extension.html?q=gen%3Acustom-write#%28def._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._gen~3acustom-write%29%29

~Leif Andersen

**Comment by soegaard** [comment]
For my purpose it doesn't matter whether the structures are transparent or prefab.
That said the standard is to use #:transparent unless one needs serialization.

From the Guide:

TRANSPARENT : Anyone can inspect or create an instance without access to the structure-type declaration, which means that the value printer can show the content of an instance. All instance creation passes through a constructor guard, however, so that the content of an instance can be controlled, and the behavior of instances can be specialized through properties. Since the structure type is generated by its definition, instances cannot be manufactured simply through the name of the structure type, and therefore cannot be generated automatically by the expression reader.

PREFAB : Anyone can inspect or create an instance at any time, without prior access to a structure-type declaration or an example instance. Consequently, the expression reader can manufacture instances directly. The instance cannot have a constructor guard or properties.

Since the expression reader can generate prefab instances, they are useful when convenient serialization is more important than abstraction. Opaque and transparent structures also can be serialized, however, if they are defined with serializable-struct as described in Datatypes and Serialization.

**Comment by LeifAndersen** [comment]
Oh cool. I didn't realize the standard was to make it #:transparent.

I'm good either way really.

~Leif Andersen

**Comment by akeep** [comment]
I’m happy to change this to #:transparent.  I’ve got other fixes for error messages, etc. to fix, and I can make that change as well.

-andy:)

**Comment by LeifAndersen** [comment]
Cool.

/me goes back to porting the documentation to scribble.

~Leif Andersen

**Pull request merged**
